build_binary:
    pre_flight: 
        - cd ../ && echo $PWD
    script: echo 'hello there'
    builder: 'particle'
    artifacts:
        -  'testing/'
    post_flight: 
        - echo "finito la musica"
