PROJECT_NAME := aws_demos


export AMAZON_FREERTOS_PATH := $(SPN_BUILDER_SDK)
export IDF_PATH := $(AMAZON_FREERTOS_PATH)/lib/third_party/mcu_vendor/espressif/esp-idf
EXTRA_COMPONENT_DIRS := $(SPN_PROJECT_DIR)/esp32_devkitc_esp_wrover_kit/common/application_code/espressif_code

include $(IDF_PATH)/make/project.mk
